import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/auth'
import { prisma } from '@/lib/prisma'
import { sendEmail } from '@/lib/email/email-service'

// POST /api/client-approval/[stageId]/aaron-approve - Aaron approves renderings for client approval
export async function POST(
  request: NextRequest,
  { params }: { params: { stageId: string } }
) {
  try {
    const session = await getSession()
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Check if user is Aaron or has admin privileges
    if (session.user.role !== 'OWNER' && session.user.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Only Aaron can approve renderings' }, { status: 403 })
    }

    const { stageId } = await params
    const body = await request.json()
    const { approved, notes } = body

    // Get the current version
    const currentVersion = await prisma.clientApprovalVersion.findFirst({
      where: {
        stageId
      },
      include: {
        stage: {
          include: {
            room: {
              include: {
                project: true
              }
            }
          }
        }
      },
      orderBy: {
        createdAt: 'desc'
      }
    })

    if (!currentVersion) {
      return NextResponse.json({ error: 'Version not found' }, { status: 404 })
    }

    // Update the version with Aaron's approval
    const updatedVersion = await prisma.clientApprovalVersion.update({
      where: {
        id: currentVersion.id
      },
      data: {
        approvedByAaron: approved,
        aaronApprovedAt: approved ? new Date() : null,
        aaronApprovedById: approved ? session.user.id : null,
        notes: notes || null,
        status: approved ? 'READY_FOR_CLIENT' : 'DRAFT'
      }
    })

    // Create activity log
    await prisma.activity.create({
      data: {
        stageId: currentVersion.stageId,
        type: approved ? 'AARON_APPROVED' : 'AARON_REJECTED',
        message: approved 
          ? `Aaron approved ${currentVersion.version} - Aaron approved renderings for client approval${notes ? ` with notes: \"${notes}\"` : ''}`
          : `Aaron rejected ${currentVersion.version}${notes ? ` with notes: \"${notes}\"` : ''}`,
        userId: session.user.id
        // timestamp field is auto-generated by @default(now())
      }
    })

    // Send email notification to Shaya when Aaron approves
    if (approved) {
      try {
        const shaya = await prisma.user.findFirst({
          where: {
            email: 'shaya@meisnerinteriors.com'
          },
          select: {
            id: true,
            name: true,
            email: true,
            emailNotificationsEnabled: true
          }
        })

        if (shaya && shaya.emailNotificationsEnabled) {
          const roomName = currentVersion.stage.room.name || currentVersion.stage.room.type.replace('_', ' ').toLowerCase()
          const projectName = currentVersion.stage.room.project.name
          const roomUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/projects/${currentVersion.stage.room.project.id}/rooms/${currentVersion.stage.roomId}?stage=${currentVersion.stageId}`
          const approverName = session.user.name || 'Aaron'

          console.log(`[Email] Sending Aaron approval notification to Shaya for ${roomName} (${projectName})...`)
          
          await sendEmail({
            to: shaya.email,
            subject: `${roomName} (${projectName}) - Aaron Approved`,
            html: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aaron Approved</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f8fafc; line-height: 1.6;">
    <div style="max-width: 640px; margin: 0 auto; background: white;">
        <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 40px 32px; text-align: center;">
            <img src="${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/meisnerinteriorlogo.png" 
                 alt="Meisner Interiors" 
                 style="max-width: 200px; height: auto; margin-bottom: 24px; background-color: white; padding: 16px; border-radius: 8px;" />
            <h1 style="margin: 0; color: white; font-size: 28px; font-weight: 600; letter-spacing: -0.025em;">Aaron Approved</h1>
            <p style="margin: 8px 0 0 0; color: #d1fae5; font-size: 16px; font-weight: 400;">${projectName}</p>
        </div>
        
        <div style="padding: 40px 32px;">
            <p style="margin: 0 0 24px 0; color: #1e293b; font-size: 16px;">Hi ${shaya.name},</p>
            
            <p style="margin: 0 0 16px 0; color: #475569; font-size: 15px; line-height: 1.7;">
                <strong>${approverName}</strong> has approved the renderings in <strong>Client Approval</strong>.
            </p>
            
            <div style="background: #f0fdf4; border-left: 4px solid #10b981; padding: 20px; margin: 24px 0; border-radius: 6px;">
                <p style="margin: 0 0 8px 0; color: #065f46; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Approved</p>
                <p style="margin: 0 0 8px 0; color: #1e293b; font-size: 15px;"><strong>Project:</strong> ${projectName}</p>
                <p style="margin: 0; color: #1e293b; font-size: 15px;"><strong>Room:</strong> ${roomName}</p>
            </div>
            ${notes ? `
            <div style="background: #f8fafc; border-left: 4px solid #64748b; padding: 20px; margin: 24px 0; border-radius: 6px;">
                <p style="margin: 0 0 8px 0; color: #475569; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Notes from Aaron</p>
                <p style="margin: 0; color: #1e293b; font-size: 14px; line-height: 1.6;">${notes}</p>
            </div>` : ''}
            
            <p style="margin: 24px 0 0 0; color: #475569; font-size: 15px; line-height: 1.7;">
                This room is now approved and ready for the next steps.
            </p>
            
            <div style="text-align: center; margin: 32px 0;">
                <a href="${roomUrl}" 
                   style="background: #10b981; color: white; padding: 16px 32px; border-radius: 8px; text-decoration: none; font-size: 16px; font-weight: 600; display: inline-block; box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);"
                   target="_blank">View Room</a>
            </div>
        </div>
        
        <div style="background: #f8fafc; border-top: 1px solid #e2e8f0; padding: 20px; text-align: center;">
            <div style="color: #1e293b; font-size: 14px; font-weight: 600; margin-bottom: 12px;">Meisner Interiors Team</div>
            <div style="margin-bottom: 12px;">
                <a href="mailto:projects@meisnerinteriors.com" 
                   style="color: #059669; text-decoration: none; font-size: 13px; margin: 0 8px;">projects@meisnerinteriors.com</a>
                <span style="color: #cbd5e1;">•</span>
                <a href="tel:+15147976957" 
                   style="color: #059669; text-decoration: none; font-size: 13px; margin: 0 8px;">514-797-6957</a>
            </div>
            <p style="margin: 0; color: #94a3b8; font-size: 11px;">&copy; 2025 Meisner Interiors. All rights reserved.</p>
        </div>
    </div>
</body>
</html>`,
            text: `Hi ${shaya.name},\n\n${approverName} has approved the renderings in Client Approval.\n\nProject: ${projectName}\nRoom: ${roomName}${notes ? `\n\nNotes from Aaron: ${notes}` : ''}\n\nThis room is now approved and ready for the next steps.\n\nView the room: ${roomUrl}\n\nBest regards,\nThe Team`
          })
          
          console.log(`[Email] Aaron approval notification sent to Shaya`)
        } else if (shaya && !shaya.emailNotificationsEnabled) {
          console.log(`[Email] Skipping notification to Shaya (email notifications disabled)`)
        } else {
          console.log(`[Email] Shaya user not found in database`)
        }
      } catch (emailError) {
        console.error('[Email] Failed to send Aaron approval notification to Shaya:', emailError)
        // Don't fail the main operation if email notification fails
      }
    }

    return NextResponse.json({ 
      success: true,
      version: updatedVersion
    })

  } catch (error) {
    console.error('Error processing Aaron approval:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}